### ISSUE TITLE
Error loading editor

### ISSUE THREAD

**Issue by azefio** [RayCarrot/Ray1Editor#2]
When i try to load a level of Rayman PS1 US, it say Could not find SLUS-000.05 although it's there.

plz help

**Comment by RayCarrot** [comment]
Does the file (with that exact file name) exist in the same folder that you selected when adding the game? You can double check which folder you selected by pressing the edit button when selecting the game in the menu.

**Comment by azefio** [comment]
Yes it does.

**Comment by RayCarrot** [comment]
If you select the game in the menu and press the folder button can you then send me a screenshot of the files which show there?

**Comment by azefio** [comment]
There:
![Capture](https://user-images.githubusercontent.com/67216066/130754397-c00fae4a-37c5-47a0-93c5-05ad4184b71a.PNG)

**Comment by RayCarrot** [comment]
Thanks! I can see the issue now. Since you have file extensions hidden in your File Explorer it means you don't see the full file name. If you press on View in the File Explorer and then check to show file extensions you'll see that the names of your files there don't fully match. It appears they are renamed .bin and .cue files which won't work.
So to get the game working in the editor you need to extract the files from within the disc. Using the disc image (.bin/.cue) directly won't work. To simplify this process I've uploaded an already extracted folder here (the PS1 edit kit): https://raym.app/ray1editor/
You can simply download that, extract the contents and set the game folder to the decompressed Files files. In there you'll see the correct SLUS-000.05 file.

**Comment by azefio** [comment]
Okay it works, thank you very much !
